### ISSUE TITLE
Add tracking script

### ISSUE THREAD

**Issue by 0xFireball** [0xFireball/KQAnalytics3#2]
Tracking script will automatically set up analytics in the webpage.

Status:
- [x] Add built-in tracking script
- [x] Log requests to tracking script
- [ ] Implement tracking script
  - [ ] Automatically send basic events
  - [ ] Inject an API to allow custom events from user code

**Comment by 0xFireball** [comment]
duplicate of #4
